version: '3.8'

services:
  app:
    container_name: todo_list_backend
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    external_links:
      - db

  db:
    container_name: todo_list_db
    image: postgres:9-alpine
    restart: always
    tty: true
    environment:
      POSTGRES_USER: todo_list
      POSTGRES_PASSWORD: todo-123456
      POSTGRES_DB: todo_list_local
    ports:
      - "5432:5432"
